"""initial schema

Revision ID: 31faa0782ecb
Revises: 
Create Date: 2026-09-20 21:07:00.521203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31faa0782ecb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), server_default='en', nullable=False),
    sa.Column('role', sa.String(length=32), server_default='beneficiary', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("preferred_language IN ('en', 'kn', 'hi')", name='ck_users_preferred_language'),
    sa.CheckConstraint("role IN ('beneficiary', 'officer')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('location_label', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('business_category', sa.String(length=64), nullable=False),
    sa.Column('margin_paise', sa.BigInteger(), nullable=False),
    sa.Column('project_cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('loan_paise', sa.BigInteger(), nullable=False),
    sa.Column('scheme', sa.String(length=16), nullable=False),
    sa.Column('lokscore', sa.Float(), nullable=False),
    sa.Column('lokscore_grade', sa.String(length=8), nullable=False),
    sa.Column('data_status', sa.String(length=16), nullable=False),
    sa.Column('inputs_json', sa.JSON(), nullable=False),
    sa.Column('outputs_json', sa.JSON(), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("data_status IN ('complete', 'incomplete')", name='ck_assessments_data_status'),
    sa.CheckConstraint("scheme IN ('micro', 'term')", name='ck_assessments_scheme'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scheme', sa.String(length=16), nullable=False),
    sa.Column('principal_paise', sa.BigInteger(), nullable=False),
    sa.Column('rate_bps', sa.Integer(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('moratorium_months', sa.Integer(), nullable=False),
    sa.Column('attestation_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('sanctioned_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scheme IN ('micro', 'term')", name='ck_loans_scheme'),
    sa.CheckConstraint("status IN ('active', 'closed')", name='ck_loans_status'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    op.create_table('checkins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('revenue_paise', sa.BigInteger(), nullable=False),
    sa.Column('expenses_paise', sa.BigInteger(), nullable=False),
    sa.Column('customers', sa.Integer(), nullable=False),
    sa.Column('lokscore_recomputed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'period', name='uq_checkins_loan_period')
    )
    op.create_table('repayments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('installment_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='upcoming', nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('simulated', sa.Boolean(), server_default='1', nullable=False),
    sa.CheckConstraint("status IN ('upcoming', 'paid', 'overdue')", name='ck_repayments_status'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'installment_no', name='uq_repayments_loan_installment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayments')
    op.drop_table('checkins')
    op.drop_table('loans')
    op.drop_table('assessments')
    op.drop_table('users')
    # ### end Alembic commands ###
